Repository Studio-024/self-wiser, pull requests merged in 2022-01, with the labels that each got.

#1 Component Header and initial configs
  assets/fonts/Noto-sans/NotoSans-Black.ttf
  assets/fonts/Noto-sans/NotoSans-BlackItalic.ttf
  assets/fonts/Noto-sans/NotoSans-Bold.ttf
  assets/fonts/Noto-sans/NotoSans-BoldItalic.ttf
  assets/fonts/Noto-sans/NotoSans-ExtraBold.ttf
  assets/fonts/Noto-sans/NotoSans-ExtraBoldItalic.ttf
  assets/fonts/Noto-sans/NotoSans-ExtraLight.ttf
  assets/fonts/Noto-sans/NotoSans-ExtraLightItalic.ttf
  assets/fonts/Noto-sans/NotoSans-Italic.ttf
  assets/fonts/Noto-sans/NotoSans-Light.ttf
  assets/fonts/Noto-sans/NotoSans-LightItalic.ttf
  assets/fonts/Noto-sans/NotoSans-Medium.ttf
  assets/fonts/Noto-sans/NotoSans-MediumItalic.ttf
  assets/fonts/Noto-sans/NotoSans-Regular.ttf
  assets/fonts/Noto-sans/NotoSans-SemiBold.ttf
  assets/fonts/Noto-sans/NotoSans-SemiBoldItalic.ttf
  assets/fonts/Noto-sans/SIL Open Font License.txt
  assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
  assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
  assets/fonts/Nunito/OFL.txt
  assets/fonts/Nunito/README.txt
  assets/fonts/Nunito/static/Nunito-Black.ttf
  assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
  assets/fonts/Nunito/static/Nunito-Bold.ttf
  assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
  assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
  assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
  assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
  assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
  assets/fonts/Nunito/static/Nunito-Italic.ttf
  assets/fonts/Nunito/static/Nunito-Light.ttf
  assets/fonts/Nunito/static/Nunito-LightItalic.ttf
  assets/fonts/Nunito/static/Nunito-Medium.ttf
  assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
  assets/fonts/Nunito/static/Nunito-Regular.ttf
  assets/fonts/Nunito/static/Nunito-SemiBold.ttf
  assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
  assets/fonts/Roboto/LICENSE.txt
  assets/fonts/Roboto/Roboto-Black.ttf
  assets/fonts/Roboto/Roboto-BlackItalic.ttf
  assets/fonts/Roboto/Roboto-Bold.ttf
  assets/fonts/Roboto/Roboto-BoldItalic.ttf
  assets/fonts/Roboto/Roboto-Italic.ttf
  assets/fonts/Roboto/Roboto-Light.ttf
  assets/fonts/Roboto/Roboto-LightItalic.ttf
  assets/fonts/Roboto/Roboto-Medium.ttf
  assets/fonts/Roboto/Roboto-MediumItalic.ttf
  assets/fonts/Roboto/Roboto-Regular.ttf
  assets/fonts/Roboto/Roboto-Thin.ttf
  assets/fonts/Roboto/Roboto-ThinItalic.ttf
  components/header/index.tsx
  components/header/style.module.scss
  pages/index.tsx
  pages/posts/index.tsx
  styles/fonts.scss
  styles/globals.scss
  styles/utils.module.scss
  styles/vars.scss
  yarn.lock
Labels: enhancement

#3 hotfix/ansi-regex
  package.json
  yarn.lock
Labels: wontfix

#6 Feature/article
  src/components/header/style.module.scss
  src/pages/posts/index.tsx
  src/pages/posts/models/data.ts
  src/pages/posts/style.module.scss
  src/styles/globals.scss
Labels: feature

#4 Feature/tag
  src/components/tags/index.tsx
  src/components/tags/style.module.scss
  src/pages/posts/index.tsx
  src/pages/posts/models/data.ts
Labels: feature

#7 Feature/posts profile
  src/components/postProfile/index.tsx
  src/components/postProfile/style.module.scss
  src/pages/posts/index.tsx
  src/pages/posts/models/Alexandreicon.jpg
  src/pages/posts/models/data.ts
Labels: feature
